config/routes.rb
Rails.application.routes.draw do
  resources :sandwich_ingredients, only: [:new, :create, :edit, :update, :destroy]
  resources :ingredients
  resources :sandwiches
  resources :replies, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy, :show], param: :username
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post '/ingredients/search', to: 'ingredients#search'
  post '/sandwiches/search', to: 'sandwiches#search'
  
  root 'static#home', as: 'stranger_home'
  get '/home', to: 'users#home', as: 'home'
  get '/about', to: 'static#about', as: 'about'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get 'users/:username/sandwiches', to: "users#sandwiches", as: 'user_sandwich'
  get '/stats', to: 'users#stats', as: 'stats'
  post '/add_ingredient', to: 'sandwiches#add_ingredient', as: 'add_ingredient'

  get '/403', to: 'errors#forbidden', as: 'forbidden'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  resources :photos

end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :replies, through: :comments
    has_many :sandwich_ingredients
    has_many :ingredients, through: :sandwich_ingredients

    has_one_attached :sandwich_photo

    validates :title, presence: true

    accepts_nested_attributes_for :ingredients

    def average_rating
        sum = self.comments.average(:rating)
        !sum ? 0 : sum.truncate(3)
    end

    def is_vegan?
        if !self.ingredients.where('is_meat = true').empty? || !self.ingredients.where('is_dairy_or_egg = true').empty?
            return false
        else 
            return true
        end
    end

    def is_vegetarian?
        if !self.ingredients.where('is_meat = true').empty?
            return false
        else 
            return true
        end
    end

    def is_gluten_free?
        if !self.ingredients.where('is_gluten_free = false').empty?
            return false
        else 
            return true
        end
    end

    def is_kosher?

    end

    def self.restrict_by_category(category)
        case category
        when "Vegan"
            self.select{|s| s.is_vegan?}
        when "Vegetarian"
            self.select{|s| s.is_vegetarian?}
        when "Gluten-Free"
            self.select{|s| s.is_gluten_free?}
        when "All"
            self.all
        end
    end

    def self.name_search(input)
        string = "%#{input}%"
        self.where("title LIKE ?", string)
    end

    def self.description_search(input)
        string = "%#{input}%"
        self.where("description LIKE ?", string)
    end
    
    def self.ingredient_search(input)
        string = "%#{input}%"
        self.joins(:ingredients).where("name LIKE ?", string)
    end

    def self.consolidate_searches(input)
        new_array = []
        new_array << self.name_search(input)
        new_array << self.description_search(input)
        new_array << self.ingredient_search(input)
        array = new_array.flatten.uniq
    end

    def ingredient_quantity(id)
        ingredient = Ingredient.find(id)
        relation = SandwichIngredient.where('sandwich_id LIKE ? AND ingredient_id LIKE ?', self.id, ingredient.id)
        relation.first.quantity if !relation.empty?
    end

    def num_comments
        Comment.where('sandwich_id LIKE ?', self.id).count
    end

    def self.sort_by_commented
        # lowest is 0 highest is -1
        array = Sandwich.all.sort_by{|s| s.num_comments}
    end

    def self.most_commented
        com = Comment.group(:sandwich_id).count
        id = com.key(com.values.max)
        Sandwich.find(id)
    end

    def self.sort_by_rating
        # lowest is 0 highest is -1
        Sandwich.all.sort_by{|s| s.average_rating}
    end

    def self.highest_rated
        Sandwich.all.max_by{|s| s.average_rating}
    end
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
    CATEGORIES = ['All', 'Vegan', 'Vegetarian', 'Gluten-Free']
    before_action :must_be_logged_in, only: [:new, :edit, :destroy, :add_ingredient]
    
    def index
        @sandwiches = Sandwich.all.sort_by{|s| s.title}
        @categories = CATEGORIES
    end

    def new
        @sandwich = Sandwich.new
    end

    def create
        sandwich = Sandwich.new(sandwich_params)
        user = User.find(params[:sandwich][:user_id])
        sandwich.user = user
        sandwich.save
        if !sandwich.errors.full_messages.empty?
            flash[:error] = sandwich.errors.full_messages[0]
            return redirect_to new_sandwich_path
        end
        redirect_to edit_sandwich_path(sandwich)
    end

    def show
        @sandwich = Sandwich.find(params[:id])
        
    end

    def edit
        @sandwich = Sandwich.find(params[:id])
        @ingredients = Ingredient.all.sort_by{|i| i.name}
        @ingredient = Ingredient.new
        @type_of = ['Bread', 'Condiment', 'Filling']
        @categories = CATEGORIES
    end

    def update
        sandwich = Sandwich.find(params[:id])
        sandwich.ingredients.clear
        ingredients = params[:sandwich][:ingredients]
        ingredients.each do |ing|
            thing = Ingredient.find_by(name: ing)
            quantity = params[:sandwich][:quantity][ing]
            sandwich_ingredient = SandwichIngredient.create(sandwich_id: sandwich.id, ingredient_id: thing.id, quantity: quantity)
        end
        redirect_to sandwich_path(sandwich)
    end

    def destroy
        @sandwich = Sandwich.find(params[:id])
        @sandwich.destroy
        redirect_to '/sandwiches'
    end

    def search
        @categories = CATEGORIES
        sandwiches_by_search = Sandwich.consolidate_searches(params[:search][:name])
        sandwiches_by_category = Sandwich.restrict_by_category(params[:category])
        @sandwiches = (sandwiches_by_category & sandwiches_by_search).sort_by{|s| s.title}
        render 'index'
    end

    def add_ingredient
        ingredient = Ingredient.create(ingredient_params)
        sandwich_ingredient = SandwichIngredient.create(sandwich_id: params[:ingredient][:sandwich_id], ingredient_id: ingredient.id, quantity: params[:ingredient][:quantity])
        sandwich = Sandwich.find(params[:ingredient][:sandwich_id])
        if !ingredient.errors.full_messages.empty?
            # byebug
            flash[:error] = ingredient.errors.full_messages[0]
            return edit_sandwich_path(sandwich)
        end
        redirect_to edit_sandwich_path(sandwich)
    end

    private

    def sandwich_params
        params.require(:sandwich).permit(:title, :instructions, :description, :img_url, :ingredients, :sandwich_photo)
    end
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/views/sandwiches/_details.html.erb
<div class='text-center'>
    <h2>Average Rating: <%= @sandwich.average_rating%><br><br>
    <img class='rounded-corners' src=
    <% if @sandwich.sandwich_photo.attached? %>
        <%= url_for(@sandwich.sandwich_photo) %> 
    <% else %>
        <%= "/assets/#{@sandwich.img_url}" %>
    <% end %> width="200">
    <h2>Description:</h2>
    <p><%= @sandwich.description %>
    <h2>Ingredients:</h2>
    <div class='text-left container'>
    <ul>
    <%@sandwich.ingredients.each do |i|%>
    <li><%= link_to i.name, ingredient_path(i) %> - <%= @sandwich.ingredient_quantity(i.id)%></li>
    <%end%>
    </ul>
    </div>
    <h2>Instructions:</h2>
    <p><%= @sandwich.instructions %>
</div>

app/views/sandwiches/_edit.html.erb
<div>
    <%= form_with model: sandwich do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'w-50' %><br>
        <%= f.label :description %>
        <%= f.text_area :description, class: 'w-50'  %><br>
        <%= f.label :instructions %>
        <%= f.text_area :instructions, class: 'w-50'  %><br>
        <%= f.label :ingredients %><br>
        <div class='checkbox row col-12'>
        <% ingredients.each do |i| %>
        <div class= 'col-4'> <%= f.label i.name, {class: 'col-3'} %>:<%= f.check_box :ingredients, { multiple: true, checked: sandwich.ingredients.include?(i), class: 'col-1'}, i.name, false %> - <%= f.text_field "quantity[#{i.name}]", value: sandwich.ingredient_quantity(i.id) %></div>
        <% end %>
        </div>
        <br>
        <%= f.submit class: 'w-25' %>
    <% end %>
<div>

app/views/sandwiches/edit.html.erb
<div class='container'>
    <h1 class='text-center'>Edit Sandwich</h1>
</div>
<div class='text-center'>
    <h1><%= @sandwich.title %></h1>
    <%= render 'details' %>
</div>
<br>
<br>
<div class='text-center'>
    <h4>Modify your Sandwich</h4>
    <%= render partial: '/ingredients/new', locals: {sandwich: @sandwich, type_of: @type_of } %>
    <%= render partial: 'edit', locals: {sandwich: @sandwich, ingredients: @ingredients} %><br>
    <%= flash[:error] %>
</div>

app/views/sandwiches/index.html.erb
<h1 class='text-center'>Browse Sandwiches</h1>

<div class='container text-center'>
    <%= form_tag('/sandwiches/search')%>
    <%= label_tag(:search, 'Search')%>
    <%= search_field(:search, :name, {class: 'w-50'})%><br>
    <%= label_tag(:search, 'Filter results by')%>
    <%= select_tag('category', options_for_select(@categories.map{ |c| [c,c] }))%>
    <%= submit_tag "Search", {class: 'w-25'} %>
</div>
<br>
<br>
<div class='col-10 container mt-5'>
    <ul class="list-unstyled row">
        <% @sandwiches.each do |s| %>
        <li class="list-group-item col-sm-6 col-md-4 col-lg-2 border-0">
            <figure class='text-center'>
            <img class='round' src=
            <% if s.sandwich_photo.attached? %>
                <%= url_for(s.sandwich_photo)%>
            <% else %>
                <%= "/assets/#{s.img_url}" %> 
            <% end %> width="100" height='100'>
            <figcaption><%= link_to s.title, sandwich_path(s) %> <br> <%= s.average_rating %> stars</figcaption>
            </figure>
            </li>
        <% end %>
    </ul>
</div>

<div class='container text-center mb-5'>
<button><%= link_to "Contribute a Sandwich", new_sandwich_path, {class: 'text-decoration-none text-dark'} %></button>
</div>

app/views/sandwiches/new.html.erb
<div class='text-center container'>
    <h1>New Sandwich</h1>

    <div class='container'>
        <p>Please name and describe your sandwich <br> You will add ingredients on the next page</p>
        <%= form_with model: @sandwich do |f| %>
            <%= f.hidden_field :user_id, value: session[:user_id] %>
            <div class='form-group'>
            <%= f.label :title %><br>
            <%= f.text_field :title, {class: 'w-100'} %><br>
            </div>
            <div class='form-group'>
            <%= f.label :description %><br>
            <%= f.text_area :description, {class: 'w-100'} %><br>
            </div>
            <%= f.label :instructions %><br>
            <%= f.text_area :instructions, {class: 'w-100'} %><br>
            <div class='form-group'>
            <%= f.label 'Upload a Photo' %><br>
            <%= f.file_field :sandwich_photo %><br><br>
            </div>
            <%= f.submit %>
        
        <%end%>
        <br>
        <%= flash[:error] %>
    </div>
</div>

app/views/sandwiches/show.html.erb
<script>
    function toggleHidden(id) {
        var x = document.getElementById(id);
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>

<div id='sandwich-information' class='text-center container shadow mb-5'><h1><%= @sandwich.title %></h1>
    <h3>By: <%=link_to @sandwich.user.display_name, user_path(@sandwich.user.username) %></h3>
<% if @sandwich.user.id == session[:user_id] %>
    <p><%= link_to "Delete this Sandwich", sandwich_path(@sandwich), :data => {:confirm => "You sure?", :method => "delete"} %> - <%= link_to "Edit this Sandwich", edit_sandwich_path(@sandwich) %>
<%end%>
    <div class='row'>
        <div class='col-7'>
            <%= render 'details'%><br>
        </div>
        <div class='text-center col-5'>
            <br><h3>Leave a Comment:</h3>
            <%= render partial: '/comments/form', locals: {sandwich: @sandwich} %>
        </div>
        <div class='container'>
            <h3><%= flash[:message] %></h3>
        </div>
    </div>
</div>

<div id='comment-container' class='container align-content-center mb-5'>
    <% if !@sandwich.comments.empty? %>
        <h2 class='text-center'>Comments:</h2>
    <% end %>
    <%@sandwich.comments.each do |com|%>
    <div id='one-single-comment' class='shadow p-3 w-75 text-center content-box mb-3'>
        <% if !com.content.empty? %>
            <% if com.user.is_deleted == true %>
                <% name = 'Inactive User'%>
            <% else %>
                <% name = com.user.display_name %>
            <% end %>
            <h4 class='font-italic'><%= com.title%></h4>
            <h6>Rating: <%=com.rating%> - <%= name %>, commented at: <%= com.created_at %><h6>
            <div class='com-ital'>
                <p class='p-3 font-italic'><%= com.content %></p>
            </div>
            <% if com.user_id == session[:user_id] %>
                <%= link_to "Delete Comment", comment_path(comment_id: com.id, sandwich_id: @sandwich.id), method: :delete, data: {confirm: "Are you sure?"}%>
            <% end %>
        <%end%>
        <% if !com.replies.empty? %>
            <h4>Replies:</h4>
        <% end %>
        <%com.replies.each do |r|%>
            <% if r.user.is_deleted == true %>
                <% name = 'Inactive User'%>
            <% else %>
                <% name = r.user.display_name %>
            <% end %>
            <div>
                <p><%= name %>, replied at: <%= r.created_at %></p>
            </div>
            <div class='com-ital'>
                <p class='font-italic'><%= r.content %></p>
            </div>
            <% if r.user.id == session[:user_id] %>
                <%= link_to "Delete Reply", reply_path(reply_id: r.id, sandwich_id: @sandwich.id), method: :delete, data: {confirm: "Are you sure?"}%>
            <% end %>
        
        <% end %>
        <% if !com.content.empty? %>
            <p><button class='mt-2' onclick="toggleHidden(<%= com.id %>)">Reply to this Comment</button></p>
            <div style='display: none' id=<%= com.id %>><%= render partial: '/replies/form', locals: {comment: com} %></div>
        <% end %>
        
    </div>
    <% end %>
    </div>
</div>