config/routes.rb
Rails.application.routes.draw do
  resources :sandwich_ingredients, only: [:new, :create, :edit, :update, :destroy]
  resources :ingredients
  resources :sandwiches
  resources :replies, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy, :show], param: :username
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post '/ingredients/search', to: 'ingredients#search'
  post '/sandwiches/search', to: 'sandwiches#search'
  
  root 'static#home', as: 'stranger_home'
  get '/home', to: 'users#home', as: 'home'
  get '/about', to: 'static#about', as: 'about'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get 'users/:username/sandwiches', to: "users#sandwiches", as: 'user_sandwich'
  get '/stats', to: 'users#stats', as: 'stats'
  post '/add_ingredient', to: 'sandwiches#add_ingredient', as: 'add_ingredient'

  get '/403', to: 'errors#forbidden', as: 'forbidden'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  resources :photos

end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
    has_many :sandwiches
    has_many :replies

    has_one_attached :avatar

    validates :username, presence: true
    validates :username, uniqueness: true
    has_secure_password
    validates :display_name, presence: true
    validates :age, numericality: {min: 13}
    validates :email, presence: true
    validates :email, uniqueness: true
    validate :no_spaces
    
    def no_spaces
        errors.add(:username, 'may not contain spaces') if /\s/.match(username)
    end

    def email_is_valid
        errors.add(:email, 'is not a valid e-mail address') unless /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.match(email)
    end

    def average_rating
        if self.sandwiches.empty?
            average_rating = 0
        else
            sandwich_ratings = self.sandwiches.map{|sandwich| sandwich.average_rating}
            average_rating = sandwich_ratings.inject(0){|sum, n| sum + n} / sandwich_ratings.length
        end
    end

    def self.sort_by_rating
        self.all.sort_by{|user| user.average_rating}
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy, :sandwiches]
    before_action :must_be_logged_in, only: [:show, :edit, :update, :destroy, :home]
    def index
      @users = User.all
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to home_path
        else
            render :new
        end
    end

    def edit
    end

    def update
    end

    def destroy
        @user.is_deleted = true
        @user.save
        redirect_to logout_path
    end

    def home
        @user = current_user
        @sandwich = Sandwich.all.sample
        user_sandwiches_by_rating = @user.sandwiches.sort_by{|sandwich| sandwich.average_rating}
        @top_sandwich = user_sandwiches_by_rating.last
        @bottom_sandwich = user_sandwiches_by_rating.first
    end

    def sandwiches
        @sandwiches = @user.sandwiches
    end

    def stats
        @hall_of_fame = User.sort_by_rating.reverse.slice(0, 5)
        @hall_of_shame = User.sort_by_rating.slice(0, 5)
        @highest_rated = Sandwich.highest_rated
        @most_commented = Sandwich.most_commented

    end

    private

    def set_user
        @user = User.find_by!(username: params[:username])
    end

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation, :display_name, :age, :bio, :img_url, :email, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for user do |f| %>
<div class='container shadow text-center mt-3 pt-4 pb-4'>
  <%= f.label 'Username:' %>
  <%= f.text_field :username, {class: 'w-50'} %>
  <br><br>
  <%= f.label :display_name %>
  <%= f.text_field :display_name, {class: 'w-50'} %>
  <br><br>  
  <%= f.label :password %>
  <%= f.password_field :password, {class: 'w-50'} %>
  <br><br>  
  <%= f.label "Confirm" %>
  <%= f.password_field :password_confirmation, {class: 'w-50'} %>
  <br><br> 
  <%= f.label "E-mail address" %>
  <%= f.text_field :email, {class: 'w-50'} %> 
  <br><br> 
  <%= f.label :age %>
  <%= f.number_field :age, {class: 'w-50'} %>
  <br>
  <%= f.label :bio %>
  <%= f.text_area :bio, {class: 'w-50'} %>
  <br><br>
  <%= f.label "Upload an Image to be Used as Your Avatar" %>
  <%= f.file_field :avatar %><br><br>
  <%= f.submit %>
  </div>
<% end %>

<% if user.errors.any? %>
  <p><%= pluralize(user.errors.count, 'error') %> prevented you from creating an account:</p>
  <ul>
    <% user.errors.full_messages.each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
<% end %> 

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/home.html.erb
<h1 class="text-center">Welcome, <%= @user.display_name %>!</h1>
<br>
<br>
<% if @top_sandwich && @bottom_sandwich %>
<div class="container">
<div class="row">
<div class="col d-inline-block">
<p>Sandwich of the moment: <%= link_to @sandwich.title, @sandwich %></p>
<img src=
    <% if @sandwich.sandwich_photo.attached? %>
        <%= url_for(@sandwich.sandwich_photo)%>
    <% else %>
        <%= "/assets/#{@sandwich.img_url}" %> 
      <% end %> width="300">
</div>
<div class="col d-inline-block">
<p>Your top-rated sandwich: <%= link_to @top_sandwich.title, @top_sandwich %></p>
<img src=
    <% if @top_sandwich.sandwich_photo.attached? %>
        <%= url_for(@top_sandwich.sandwich_photo)%>
    <% else %>
        <%= "/assets/#{@top_sandwich.img_url}" %> 
      <% end %> width="300">
</div>
<div class="col d-inline-block">
<p>Your bottom-rated sandwich: <%= link_to @bottom_sandwich.title, @bottom_sandwich %></p>
<img src=
    <% if @bottom_sandwich.sandwich_photo.attached? %>
        <%= url_for(@bottom_sandwich.sandwich_photo)%>
    <% else %>
        <%= "/assets/#{@bottom_sandwich.img_url}" %> 
      <% end %> width="300">
</div>
</div>
</div>
<% else %>
<div class="container">
<div class="row">
<div class="col d-inline-block">
<p>Sandwich of the moment: <%= link_to @sandwich.title, @sandwich %></p>
<img src=
    <% if @sandwich.sandwich_photo.attached? %>
        <%= url_for(@sandwich.sandwich_photo)%>
    <% else %>
        <%= "/assets/#{@sandwich.img_url}" %> 
      <% end %> width="300">
</div>
<div class="col d-inline-block">
<p>You don't seem to have any sandwiches yet. Maybe you'd like to <%= link_to "make one", new_sandwich_path %>?</p>
</div>
</div>
</div>
<% end %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |u| %>
    <% if u.is_deleted == false %>
      <li><img src=
    <% if u.avatar.attached? %>
        <%= url_for(u.avatar)%>
    <% else %>
        <%= "/assets/#{u.img_url}" %> 
        <% end %> width="100"><%= u.username %></li>
    <% end %>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1 class='text-center'>Welcome to the Sandwich club!</h1>

<%= render 'form', user: @user %>

app/views/users/sandwiches.html.erb
<h1 class="text-center"><%= @user.username %>'s sandwiches</h1>
<br>
<div class='col-12 container'>
    <ul class="list-unstyled row">
        <% @sandwiches.each do |s| %>
            <li class="list-group-item col-3 border-0"> <img class="round" src=
    <% if s.sandwich_photo.attached? %>
        <%= url_for(s.sandwich_photo)%>
    <% else %>
        <%= "/assets/#{s.img_url}" %> 
      <% end %> width="100">  <%= link_to s.title, sandwich_path(s) %> - <%= s.average_rating %> stars</li>
        <% end %>
    </ul>
</div>

app/views/users/show.html.erb
<div class='text-center col-6' id='user-profile'>
    <h1><%= @user.username %></h1>
    <h2>aka <%= @user.display_name %></h2>
    <img src=
        <% if @user.avatar.attached? %>
            <%= url_for(@user.avatar)%>
        <% else %>
            <%= "/assets/#{@user.img_url}" %> 
        <% end %> width="200">
    <h3>Age: <%= @user.age %></h3>
    <h4>Club Member Since: <%= @user.created_at.strftime('%b. %d, %Y') %></h4> 
    <h3>Bio: </h3>
    <p><%= @user.bio %></p>
    <h2 class='mb-5'><%= link_to "#{@user.username}'s sandwiches", user_sandwich_path(@user.username) %></h2>
    <% if @user.id == session[:user_id] %>
        <h4 class='w-25 d-inline-block'><%= link_to "Edit profile", edit_user_path(@user.username) %></h4>
        <h4 class='w-25 d-inline-block'><%= link_to "Delete account", user_path(@user.username), method: :delete, data: {confirm: "Are you sure? We'll miss you!"}%></h4>
    <% end %>
</div>

app/views/users/stats.html.erb
<h1 class="text-center">Site stats</h1>
<br>
<div class="container text-center">
  <div class="row">
    <div class="col-sm">
      <h3>Hall of Fame</h3>
      <ul class="list-unstyled">
        <% @hall_of_fame.each do |user| %>
          <li class="text-center mt-2"><%= link_to user.username, user_path(user.username) %>      <img src=
            <% if user.avatar.attached? %>
              <%= url_for(user.avatar) %>
            <% else %>
              <%= "/assets/#{user.img_url}" %> 
            <% end %> width="30"></li>
        <% end %>
      </ul>
    </div>
    <div class="col-sm">
      <h3>Hall of Shame</h3>
      <ul class="list-unstyled">
        <% @hall_of_shame.each do |user| %>
          <li class="text-center mt-2"><%= link_to user.username, user_path(user.username) %>      <img src=
            <% if user.avatar.attached? %>
              <%= url_for(user.avatar) %>
            <% else %>
              <%= "/assets/#{user.img_url}" %> 
            <% end %> width="30"></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class='row mt-5'>
    <div class="col-sm">
      <h3>Most popular sandwich</h3>
      <figure>
      <img class="round m-3" src=
        <% if @highest_rated.sandwich_photo.attached? %>
          <%= url_for(@highest_rated.sandwich_photo)%>
        <% else %>
          <%= "/assets/#{@highest_rated.img_url}" %> 
        <% end %> 
      width="200">  
      <figcaption><%= link_to @highest_rated.title, sandwich_path(@highest_rated) %> - <%= @highest_rated.average_rating %> stars</figcaption>
      </figure>
    </div>
    <div class="col-sm">
      <h3>Most commented-on sandwich</h3>
      <figure>
      <img class="round m-3" src=
        <% if @most_commented.sandwich_photo.attached? %>
          <%= url_for(@most_commented.sandwich_photo)%>
        <% else %>
          <%= "/assets/#{@most_commented.img_url}" %> 
        <% end %> 
      width="200"> 
      <figcaption> <%= link_to @most_commented.title, sandwich_path(@most_commented) %> - <%= @most_commented.average_rating %> stars </figcaption>
      </figure>
    </div>
  </div>
</div>