config/routes.rb
Rails.application.routes.draw do
  resources :sandwich_ingredients, only: [:new, :create, :edit, :update, :destroy]
  resources :ingredients
  resources :sandwiches
  resources :replies, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy, :show], param: :username
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post '/ingredients/search', to: 'ingredients#search'
  post '/sandwiches/search', to: 'sandwiches#search'
  
  root 'static#home', as: 'stranger_home'
  get '/home', to: 'users#home', as: 'home'
  get '/about', to: 'static#about', as: 'about'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get 'users/:username/sandwiches', to: "users#sandwiches", as: 'user_sandwich'
  get '/stats', to: 'users#stats', as: 'stats'
  post '/add_ingredient', to: 'sandwiches#add_ingredient', as: 'add_ingredient'

  get '/403', to: 'errors#forbidden', as: 'forbidden'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  resources :photos

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :sandwich_ingredients
    has_many :sandwiches, through: :sandwich_ingredients
    has_one_attached :ingredient_photo

    before_validation :downcase_fields

    validates :name, presence: true
    validates :type_of, inclusion: {in: %w(bread filling condiment) }

    def downcase_fields
        self.type_of.downcase!
    end

    def self.restrict_by_category(category)
        category == 'All' ? self.all : self.select{|s| s.type_of == category.downcase}
    end

    def self.name_search(input)
        string = "%#{input}%"
        self.where("name LIKE ?", string)
    end

    def is_vegan
        !(self.is_meat || self.is_dairy_or_egg)
    end

    def dietary_info
        dietary_info = []
        dietary_info << "Vegetarian" unless self.is_meat
        dietary_info << "Vegan" if self.is_vegan
        dietary_info << "Gluten-free" if self.is_gluten_free
        dietary_info.join(", ")
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
    before_action :set_type_of, only: [:new, :create]
    before_action :must_be_logged_in, only: [:new, :edit, :destroy]
    def index
        @ingredients = Ingredient.all.sort_by{|i| i.name}
        @categories = ['All', 'Filling', 'Bread', 'Condiment']
    end

    def show
    end

    def new
        @ingredient = Ingredient.new
        @categories = %w(bread filling condiment) 
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
            redirect_to ingredient_path(@ingredient)
        else
            render :new
        end
    end

    def edit
        @categories = %w(bread filling condiment) 
    end

    def update
        if @ingredient.update(ingredient_params)
            redirect_to ingredient_path(@ingredient)
        else
            render :edit
        end
    end

    def destroy
        if SandwichIngredient.find_by(ingredient_id: @ingredient.id)
            flash[:message] = "You can't delete an ingredient that's in use in a sandwich."
            return redirect_to @ingredient
        else
            @ingredient.destroy
            return redirect_to ingredients_path
        end
    end

    def search
        @categories = ['All', 'Filling', 'Bread', 'Condiment']
        ingredients_by_search = Ingredient.name_search(params[:search][:name])
        ingredients_by_category = Ingredient.restrict_by_category(params[:category])
        @ingredients = (ingredients_by_category & ingredients_by_search).sort_by{|i| i.name}
        render 'index'
    end

    private

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end
    
    def set_type_of
      @categories = [['bread', 'bread'], ['filling', 'filling'], ['condiment', 'condiment']]
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<div class='container shadow text-center mt-3 pt-4 pb-4'>
  <%= form_for ingredient do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, {class: 'w-50'} %><br>
    <%= f.label :type_of %>
    <%= f.select :type_of, categories, include_blank: true %><br>
    <%= f.label "Does it have meat?" %>
    <%= f.check_box :is_meat %>
    <%= f.label "Does it contain either dairy or egg?" %>
    <%= f.check_box :is_dairy_or_egg %>
    <%= f.label "Is it gluten-free?" %>
    <%= f.check_box :is_gluten_free %><br>
    <%= f.label :ingredient_photo %>
    <%= f.file_field :ingredient_photo %><br>
    <%= f.submit %>
  <% end %>


  <% if ingredient.errors.any? %>
    <%= pluralize(ingredient.errors.count, 'error') %> prevented you
    from submitting this form:
    <ul>
      <% ingredient.errors.full_messages.each do |err| %>
        <li><%= err %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/ingredients/_new.html.erb
<div>
  <h4>To add an unlisted ingredient, please create a new ingredient below</h4>
  <%= form_with url: add_ingredient_path, scope: 'ingredient' do |f| %>
      <%= f.hidden_field :sandwich_id, value: sandwich.id %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'w-50' %>
    <br>
    <%= f.label :quantity %>
    <%= f.text_field :quantity, class: 'w-50'%>
    <br>
    <%= f.label :type_of %>
    <%= f.select :type_of, type_of, include_blank: true %>
    <br>
    <%= f.label "Does it have meat?" %>
    <%= f.check_box :is_meat %>
    <%= f.label "Does it contain either dairy or egg?" %>
    <%= f.check_box :is_dairy_or_egg %>
    <%= f.label "Is it gluten-free?" %>
    <%= f.check_box :is_gluten_free %><br>
    <%= f.label :ingredient_photo %>
    <%= f.file_field :ingredient_photo %><br>
    <%= f.submit class: 'w-25' %>
  <% end %>
  <br>
</div>

app/views/ingredients/edit.html.erb
<h1 class="text-center">Edit ingredient</h1>
<%= render 'form', ingredient: @ingredient, categories: @categories %>

app/views/ingredients/index.html.erb
<h1 class='text-center'>Ingredients</h1>
<div class='container text-center'>
    <%= form_tag('/ingredients/search')%>
    <%= label_tag(:search, 'Search')%>
    <%= search_field(:search, :name, {class: 'w-50'})%><br>
    <%= label_tag(:search, 'Filter results by')%>
    <%= select_tag('category', options_for_select(@categories.map{ |c| [c,c] }))%>
    <%= submit_tag "Search", {class: 'w-25'} %>
</div>
<div class='col-10 container mt-5'>
<ul class="list-unstyled row align-items-baseline">
  <% @ingredients.each do |i| %>
    <li class="list-group-item col-sm-6 col-md-4 col-lg-2 border-0">
    <figure class='text-center'>
    <img class='round' src=
    <% if i.ingredient_photo.attached? %>
        <%= url_for(i.ingredient_photo)%>
    <% else %>
        <%= "/assets/#{i.img_url}" %> 
    <% end %> width="100" height='100'>
    <figcaption><%= link_to i.name, i %></figcaption>
    <figcaption><%= i.dietary_info %></figcaption>
    </figure>
    </li>
  <% end %>
</ul>
</div>

<div class='container text-center mb-5'>
<button><%= link_to "Contribute an Ingredient", new_ingredient_path, {class: 'text-decoration-none text-dark'} %></button>
</div>

app/views/ingredients/new.html.erb
<h1 class="text-center">New ingredient</h1>

<%= render partial: 'form', locals: {ingredient: @ingredient, categories: @categories } %>

app/views/ingredients/show.html.erb
<div class='text-center'>
    <h1><%= @ingredient.name %></h1>
    <h2><%= @ingredient.type_of%></h2>
    <h3><%= @ingredient.dietary_info%></h3>
    <img src=
        <% if @ingredient.ingredient_photo.attached? %>
            <%= url_for(@ingredient.ingredient_photo) %> 
        <% else %>
            <%= "/assets/#{@ingredient.img_url}" %>
        <% end %> width="200"><br>
    <%= link_to "Edit", edit_ingredient_path(@ingredient) %>
    <%= link_to "Delete", @ingredient, method: :delete, data: { confirm: "Really?" } %>
    <%= flash[:message] %>
</div>