config/routes.rb
Rails.application.routes.draw do
  resources :sandwich_ingredients, only: [:new, :create, :edit, :update, :destroy]
  resources :ingredients
  resources :sandwiches
  resources :replies, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy, :show], param: :username
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post '/ingredients/search', to: 'ingredients#search'
  post '/sandwiches/search', to: 'sandwiches#search'
  
  root 'static#home', as: 'stranger_home'
  get '/home', to: 'users#home', as: 'home'
  get '/about', to: 'static#about', as: 'about'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get 'users/:username/sandwiches', to: "users#sandwiches", as: 'user_sandwich'
  get '/stats', to: 'users#stats', as: 'stats'
  post '/add_ingredient', to: 'sandwiches#add_ingredient', as: 'add_ingredient'

  get '/403', to: 'errors#forbidden', as: 'forbidden'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  resources :photos

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Chilanka|Open+Sans+Condensed:300&display=swap" rel="stylesheet">

    <title>SandwichesAClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default clearfix nav-div mb-5">
      <div class="container w-25 float-left nav-div">
        <div class="navbar-header">
          <%= link_to image_tag("/assets/logo.png", {width: '200px', id: 'logo'}) , stranger_home_path, {class: "navbar-brand text-white"} %>
        </div>
      </div>
      <div class="float-right" >
          <% if session[:user_id] %>
            <% user = User.find(session[:user_id]) %>
            <div class='float-right'><%= link_to 'Logout', logout_path %></div>
            <div class='float-right mr-3'><%= link_to 'Profile', user_path(user.username) %></div>
          <% else %>
            <div class='float-right'><%= link_to "Log in", login_path %></div>
            <div class='float-right mr-3'><%= link_to "Sign up", new_user_path %></div>
          <% end %>
          <div class='float-right mr-3'><%= link_to 'Sandwiches', sandwiches_path %></div>
          <div class='float-right mr-3'><%= link_to 'Ingredients', ingredients_path %></div>
          <div class='float-right mr-3'><%= link_to 'About Us', about_path %></div>
        </div>
    </nav>
    <div>
    <div>
    <%= yield %>
  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Chilanka|Open+Sans+Condensed:300&display=swap" rel="stylesheet">

    <title>SandwichesAClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id='session'>
      <%= yield %>
  </body>
</html>